### ISSUE TITLE
Users - Unable to change user role

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#48]
Scenario:
Select a user and change the role 

Steps:
1. Select manage users from the  users dropdown list button
2. Search user
3. Click the action button 
4. In the Role dropdown list, change the user's role
5. Click save

Observed Result:
Unable to change user role. error message displayed "Failed to update user. Please try again"

Expected Result:
Changing user role successful

![edit user role error](https://cloud.githubusercontent.com/assets/20081753/17828984/ae65c290-66d1-11e6-9e1e-8eede1c464f8.png)

**Comment by vernonminer** [comment]
Resolved

**Comment by junpaolo** [comment]
Still experiencing the same issue

![change user s role error](https://cloud.githubusercontent.com/assets/20081753/17915740/8ae35c72-69df-11e6-83c8-eb888a606a5a.png)

**Comment by vernonminer** [comment]
Retest was done prior to application update.

**Comment by junpaolo** [comment]
fixed
![change user role1](https://cloud.githubusercontent.com/assets/20081753/17994389/abd3c42e-6b8a-11e6-93db-02e78f660d07.png)

![change user role2](https://cloud.githubusercontent.com/assets/20081753/17994392/b0eeae56-6b8a-11e6-9c98-cbaf611789ba.png)
